### PR TITLE
Polish wizard

### LINKED ISSUE #214: Onboarding wizard polishing
Add some polishing to the wizard
* hover states to buttons and links
* transition to the switching of steps
* Transition to collapsing and expanding the wizard
* Hover state of X
* Initially start wizard fully open
* Blue links for "past" steps

ref #168

### PR DESCRIPTION
**Pull request by venimus**
close #214

### CODE REVIEW

**Comment by venimus** [comment]
@mradkov @thepiwo Not ready yet but could you review this part

Refactored to use the vuex state instead of localstorage directly to store the wizard state

**Comment by mradkov** [comment]
The wizard should be collapsed when user has the extension installed.

**Comment by venimus** [comment]
> The wizard should be collapsed when user has the extension installed.

I disabled this temporary for testing the PR.

**Comment by venimus** [comment]
Spacing fixed

**Pull request merged**
