### PR TITLE
Aligned icons on mobile (Dont merge yet)

### PR DESCRIPTION
**Pull request by stanislav-slavov**

### CODE REVIEW

**Comment by mradkov** [comment]
Looks good on my side.

What is the reason for holding it from merging?

**Comment by stanislav-slavov** [comment]
Another fix is being done by @venimus .

**Comment by mradkov** [comment]
> Another fix is being done by @venimus .

@venimus whats blocking the merge here?

**Comment by stanislav-slavov** [comment]
A different solution is provided by @venimus https://github.com/aeternity/aepp-raendom/pull/253

I suppose this PR is redundant.

**Comment by venimus** [comment]
> > Another fix is being done by @venimus .
> 
> @venimus whats blocking the merge here?

the bug is else where it is fixed in https://github.com/aeternity/aepp-raendom/pull/253

**Comment by venimus** [comment]
> I suppose this PR is redundant.

yes, this should be closed. It reintroduces `vertical-align` which I removed earlier due to multiple issues with it. vertical-align:middle should not be used for precision centering of images and text

**Pull request closed without merging**
